version: '3.9'

services:
  server:
    container_name: 'dominux-drive-backend'
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
