version: '3.9'

services:
  server:
    container_name: 'dominux-drive-server'
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'

  db:
    container_name: 'dominux-drive-db'
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data/
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
